#!/usr/bin/env python

import sys

from lunabotics_rqt_23_UI.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'lunabotics_rqt_23_UI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))